// Copyright 2026 David M. King
// SPDX-License-Identifier: MIT
//
// Auto-generated by the desktop sim's layout editor.
// Edit by running the sim, dragging elements, pressing S.
// Manual edits will be preserved as long as the field order
// in layout_cyd.h doesn't change.

#include "layout_cyd.h"

layout_cyd_repo_t cyd_repo_layout = {
    .title         = { .x =   4, .y =   4, .scale = 1, .r = 0xFF, .g = 0xFF, .b = 0xFF },
    .clock         = { .x = 316, .y =   4, .scale = 1, .r = 0x88, .g = 0x88, .b = 0x88, .right_align = true },
    .stars         = { .x =   4, .y =  24, .scale = 1, .r = 0xFF, .g = 0xDD, .b = 0x00 },
    .desc          = { .x =   4, .y =  44, .scale = 1, .r = 0x88, .g = 0x88, .b = 0x88 },

    .views_label   = { .x =   4, .y = 103, .scale = 1, .r = 0x40, .g = 0x80, .b = 0xFF },
    .views_bar     = { .x =  62, .y = 103, .w = 256, .h = 14 },
    .views_bignum  = { .x =  62, .y = 122, .scale = 1, .r = 0x88, .g = 0x88, .b = 0x88 },

    .clones_label  = { .x =   4, .y = 174, .scale = 1, .r = 0xFF, .g = 0xA0, .b = 0x00 },
    .clones_bar    = { .x =  62, .y = 174, .w = 256, .h = 14 },
    .clones_bignum = { .x =  62, .y = 193, .scale = 1, .r = 0x88, .g = 0x88, .b = 0x88 },
};
